package com.parkingspot.demo.dto;

public class ApplicationConstant {
	public static final String OAUTH_ENDPOINT = "https://account.api.here.com/oauth2/token";
	public static final String DISCOVER_ENDPOINT = "discover.search.hereapi.com/v1/discover";
	public static final String TOKEN= "eyJhbGciOiJSUzUxMiIsImN0eSI6IkpXVCIsImlzcyI6IkhFUkUiLCJhaWQiOiJqaXZUYkdwV0pHcVJzdDZrOW45aCIsImlhdCI6MTYwMDE0NTcwNiwiZXhwIjoxNjAwMjMyMTA2LCJraWQiOiJqMSJ9.ZXlKaGJHY2lPaUprYVhJaUxDSmxibU1pT2lKQk1qVTJRMEpETFVoVE5URXlJbjAuLl9rbm9melkzeXY4NXRVNVlLXzJaM2cuUlZvRGxjTm4xLUVuclF4UVdpVUJ5ZnViWXZVWXhLVFVBQTJGcldHV3VTRXlhdnFKdm83aTBpak1FZEhRcy1ndDBRSE5LRmdHdFI0WFNISVNDYWZVQmIwWGNtd09jeE1BelpjYm83ZzBKWHF2dEtvUWtvRzh4WDRoR2V3cVpGTUh2UUtJTktsdFBublpSTDBPT244dTJRLjgtRXhWNFE1cmdMbUhRV3M0TVM0b2V6RVdNMGRjNFphNlAyMW1mTEV1ek0.kVaNOLh1JPgwjX5933md15VFTz73O8JX8O0FU_Q7Bv4VhJSNzqc5m0v2wk8266zyqpymgszzlCI9XaK9rrRdIOGvFaaCzhi0dLIaqvW8eXok2AONwg9qD1HRSbk74L2wpkdu36vfhGaUre_fM_ggGtyRdRkgJz5KZSeX54FMmSpEmEJhem3jV9UfPirrLlNuBw--gxGqmE6NN4vpeaC9yIMEFKOJ5QFbib9_9DFbKwJ3mNWu_9ofjOrUORPDlESLa6FKKPeuOnbwxDc00g8LWYkd_khfmbPEIBK4qtCtMxup_zLwv6zrTokSN71-ROM19irkkuy1iJoLQPkzKc_Zng";
	public static final String API_KEY = "VoNjJl18K5GlFk1248a-fgYITnUb8J-rxBlPLEUcZGs";
	public static final String SEARCH_API = "geocoder.ls.hereapi.com/6.2/geocode.json";
}
