package com.parkingspot.demo.dto;

public class ApplicationConstant {
	public static final String OAUTH_ENDPOINT = "https://account.api.here.com/oauth2/token";
	public static final String DISCOVER_ENDPOINT = "discover.search.hereapi.com/v1/discover";
	public static final String TOKEN= "eyJhbGciOiJSUzUxMiIsImN0eSI6IkpXVCIsImlzcyI6IkhFUkUiLCJhaWQiOiJqaXZUYkdwV0pHcVJzdDZrOW45aCIsImlhdCI6MTYwMDEwNjQ3MywiZXhwIjoxNjAwMTkyODczLCJraWQiOiJqMSJ9.ZXlKaGJHY2lPaUprYVhJaUxDSmxibU1pT2lKQk1qVTJRMEpETFVoVE5URXlJbjAuLl9DLUdqRHJHODcxT0lvS1ZiRlZiX3cuMndYak41YVg5UE80R3ZocHVtSGwxeERHZzhaUXVLV0Q0T1JiTFR5MmQwaTFUdEoxNXlsM2R2eHQtY1NONEFwV05saDVOYUtWSDZYMmZHRjJQSlVJeHF1Q2RDRnhfOF9QZWs1SHZDdnFoNkZveWl4bHNOaFd4cTZ4SUVfTlZOc0VRR0Z0dlVOUXpQOFdUU29rS0k4Z1J3LjY4Skg1YkItR2ZPMi1DTXRYX01qNGRuamVPTTlNd3NiWWJpSHpTSmp4bWc.ciF7O-V5rcSQAIQ-hcZ9OXbPweWaVSkrN637xdY7-IOvMBvBWGePpJjc_N4npPeHgoCJys5iLcRms6TaqkgVDbLykDnvUUW1NzLOlSh17WgmY6EToHEFZ6xvC849Z25Dlc4DhXtqHWqrq15jzC5I500Gsj9hODNbl0pbNuRjj4rkDAVWW32w38FY8AhaYol4oftEVt6djTWv2QYniNckt-v94f7mDz2MOd6vH72Lw2FW0QVn5QexL7VmRjdMKTks3lczNXbvHI93jOxB_mZtNONl4wBWdAvzh-iyQgeqiwn0bnNqNaMAz1l_KCGOi3uZLJjG4atZVgFLhnnJS21vpA";
	public static final String API_KEY = "-LlplheL_upl8zMjZ3UmCDBBw3DHZ-ba0d2WbchMbkM";
	public static final String SEARCH_API = "geocoder.ls.hereapi.com/6.2/geocode.json";
}
